name: Styling
on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
jobs:
  styling:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute pint
        run: vendor/bin/pint
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: fix'
          skip_fetch: true
