name: Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Setup .env
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate --ansi
      - name: Setup database
        run: |
          php -r "file_exists('database/database.sqlite') || touch('database/database.sqlite');"
          php artisan migrate --graceful --ansi
      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
